### ISSUE TITLE
It is better to use `make installcheck` instead of nix-shell

### ISSUE THREAD

**Issue by shinyaaa** [supabase/supautils#16]
Hi!

Docs say you use nix-shell to execute regression test.
But many user cannot have environment in which NixOS can be used.
Why don't we change the method to use `make installcheck` as in the official docs?
[https://www.postgresql.org/docs/14/extend-pgxs.html](https://www.postgresql.org/docs/14/extend-pgxs.html)

Regards

**Comment by steve-chavez** [comment]
Hey Shinya,

> But many user cannot have environment in which NixOS can be used.

Do note that [Nix](https://github.com/NixOS/nix) is independent of NixOS, you can use it on any Linux distro, MacOS/FreeBSD and even on Windows through WSL.

> Why don't we change the method to use make installcheck as in the official docs?

You mean [this part](https://supabase.github.io/supautils/contributing/#testing) right?

Hm, maybe we can put the Nix env as an alternative below the official `make installcheck`?  WDYT?

(Personally I don't know of an easier/simpler way to test a C extension on different pg versions, Docker is too slow/pain for this)

**Comment by steve-chavez** [comment]
Closing this one as Nix is only a dev dependency - `make installcheck` can be used as usual.

Also Nix now works with M1 Macs(ARM) just by following the [official guide](https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation) :tada:
