### ISSUE TITLE
PostgreSQL 16 fixes the CREATEROLE problem

### ISSUE THREAD

**Issue by steve-chavez** [supabase/supautils#50]
See https://rhaas.blogspot.com/2023/01/surviving-without-superuser-coming-to.html.

We could add a note here https://github.com/supabase/supautils#role-security.

**Comment by steve-chavez** [comment]
This is already giving trouble for migrating to pg 16, many tests fail. I think we should just disable the whole reserved roles/memberships feature for pg >= 16.

**Comment by AntonOfTheWoods** [comment]
Postgresql 17 has now dropped... And supabase appears to still only support PG15. Is this issue one of the main reasons for that? I tried monkey-hits-keyboard style to get PG16 working with a few of the required extensions but quickly realised I was out of my depth. Supabase seemed to track relatively well with updates until then, and there are some interesting performance updates in there with 17.

**Comment by steve-chavez** [comment]
https://github.com/supabase/supautils/pull/86 already fixed this issue.
