### ISSUE TITLE
Can't enable extension

### ISSUE THREAD

**Issue by olirice** [supabase/supautils#62]
We get the occasional support ticket for:
```
ERROR:
Failed to toggle SUPAUTILS: failed to create pg.extensions: extension "supautils" has no installation script nor update path for version "0.1.0"Add any other context about the problem here.
```

afaik there's no reason for end users to ever enable this extension so its not a big deal, just flagging here in case its an easy thing to fix or is unexpected.

If hard to change or expected behavior please close this issue

**Comment by steve-chavez** [comment]
This is also fixed on master https://github.com/supabase/supautils/commit/b032becdd10693aac8a9b625d4db7e7430db7b52. It will get cleared on a new release/deploy.

**Comment by soedirgo** [comment]
Closing since it's been fixed with the above commit
