### ISSUE TITLE
Allow users to be created with `replication` permissions

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supautils#70]
# Chore

## Describe the chore

We allow replication on supabase (eg: the postgres role has this permission) but we do not allow our users to create _new_ roles with this permission. 

For example: 

```sql
create role foo with replication login password 'xyz';
```

![image](https://github.com/supabase/supautils/assets/10214025/ce63eea9-1cf7-41dd-9262-4f90336819f1)

Should we allow this on the platform?

**Comment by BoscoDomingo** [comment]
Yes please. This would certainly reduce the time required to set up replication, as it now forces you to email the support team and ask for this change from them

**Comment by steve-chavez** [comment]
RDS grants this ability through a role: https://stackoverflow.com/a/61912789/4692662

Not sure yet why they do that.

**Comment by BoscoDomingo** [comment]
> RDS grants this ability indirectly through a role: https://stackoverflow.com/a/61912789/4692662
> 
> Not sure yet why they do that.

Probably because the `replication` permission is built-in, whereas theirs has "magic under the hood" to achieve the same objective but circumventing the need for superuser access

**Comment by vcapretz** [comment]
we want to setup Airbyte, and it asks for a new user with `REPLICATION` access, so we would need `superuser` permission in the postgres role 😄 

https://docs.airbyte.com/integrations/sources/postgres

**Comment by soedirgo** [comment]
Resolved in https://github.com/supabase/supautils/pull/80; this will be made available on the platform soon!
